---
- name: Developed 7/1/2020 by Christopher M Johnston
  hosts: all
- name: Configure MQTT Server
  hosts: all
  become: True
  tasks:
   - name: Update
     command: sudo apt-get update -y
   - name: Upgrade
     command: sudo apt-get upgrade -y
   - name: Install python-pip3
     command: sudo apt-get install python3-pip -y
   - name: Install Git
     command: sudo apt-get install git -y
   - name: Install whois for mkpasswd
     command sudo apt-get install whois -y
   - name: Install hbmqtt
     pip:
        name: amqtt
   - name: Install MRPS
     command: git clone https://github.com/cj667113/mrp
