---
- name: Configure MQTT Server on Oracle Linux 9
  hosts: all
  become: true
  tasks:
    - name: Update all system packages
      dnf:
        name: '*'
        state: latest

  tasks:
    - name: Enable EPEL repository
      dnf:
        name: epel-release
        state: present

    - name: Install required dependencies for Python 3.7
      dnf:
        name:
          - gcc
          - openssl-devel
          - bzip2-devel
          - libffi-devel
          - zlib-devel
        state: present

    - name: Download Python 3.7 source
      get_url:
        url: https://www.python.org/ftp/python/3.7.9/Python-3.7.9.tgz
        dest: /tmp/Python-3.7.9.tgz

    - name: Extract Python 3.7 source
      unarchive:
        src: /tmp/Python-3.7.9.tgz
        dest: /tmp
        remote_src: yes

    - name: Build and install Python 3.7
      command: ./configure --enable-optimizations
      args:
        chdir: /tmp/Python-3.7.9

    - name: Make and install Python 3.7
      command: make altinstall
      args:
        chdir: /tmp/Python-3.7.9

    - name: Install required system packages
      dnf:
        name:
          - python3-pip
          - git
          - whois
        state: present

    - name: Ensure pip is up to date
      pip:
        name: pip
        state: latest
        executable: pip3

    - name: Install hbmqtt using pip
      pip:
        name: amqtt
        executable: pip3
        
    - name: Install websockets 8.1
      pip:
        name: websockets
        version: 8.1
        executable: pip3
        state: present

    - name: Clone MRPS repository
      git:
        repo: https://github.com/cj667113/mrp
        dest: /opt/mrp
        version: master
